### ISSUE TITLE
CreateTimeInEvent and CreateTimeOutEvent Arguments

### ISSUE THREAD

**Issue by sbalayan1** [learn-co-curriculum/phase-1-context-lab#10]
### Canvas Link

https://learning.flatironschool.com/courses/5841/assignments/213684?module_item_id=495556

### Concern

Arguments section in the README only specifies the date argument. Missing the employeeRecord as the first argument.

**Comment by lizbur10** [comment]
Hi @sbalayan1! If you take another look, you'll see that this lab asks students to use explicit context setting and `this` rather than passing a second argument. The functions you mentioned would be called on an instance of an employee record, e.g., `employeeRec.CreateTimeInEvent(date)`.
