### ISSUE TITLE
Mistake in Context Lab tests

### ISSUE THREAD

**Issue by jonbmoore2500** [learn-co-curriculum/phase-1-context-lab#8]
### Canvas Link

https://learning.flatironschool.com/courses/5300/assignments/179685?module_item_id=397126

### Concern

The final test in the Context Lab contains a mistake. I couldn't get the correct value to return so I did the math by hand and the expected value for the test (11880) does not equal the actual sum of the relevant data (12480).

### Suggested Changes

Check the final test and either correct the values used to run the test so that they result in the current expected value or adjust the expected value to match the inputs.

**Comment by lizbur10** [comment]
Hi @jonbmoore2500 - nice catch! This one took me a little while to track down 😄 The error has now been corrected. 

Thanks for contributing to the Flatiron School curriculum 💙
